[tool.poetry]
name = "hypermodern-python"
version = "0.1.0"
description = "The Hypermodern Python Project"
license = "MIT"
authors = ["ilkka <ilkka.kosunen@gmail.com>"]
homepage = "https://github.com/BasalGanglia/hypermodern-python"
repository = "https://github.com/BasalGanglia/hypermodern-python"
readme = "README.md"
keywords = ["hypermodern"]
packages = [{include = "hypermodern_python"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
